### ISSUE TITLE
boost pool installation?

### ISSUE THREAD

**Issue by sckott** [hrbrmstr/xslt#4]
Getting error on `./configure` for `xmlwrapp` installation

```
configure: error: cannot find Boost headers version >= 0.0.0
```

Any idea how to install that?

**Comment by hrbrmstr** [comment]
Which os?

On Wed, Jul 29, 2015 at 6:34 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
I'm on OSX Yosemite

**Comment by hrbrmstr** [comment]
`brew install boost` will take care of that (might want to get a coffee
while that's going on :-)

On Wed, Jul 29, 2015 at 6:54 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
ah, i knew boost was big, figured boost pool might be installable separately

**Comment by hrbrmstr** [comment]
sadly, no. Both Oliver & I are working on ways to not require boost for
some things but it's a super-convenient set of libraries.

On Wed, Jul 29, 2015 at 7:06 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
k, fixed
